# Data Configuration
data:
  raw_data_path: "data/raw/network_traffic.csv"
  processed_data_path: "data/processed/"
  train_test_split: 0.2
  random_state: 42

# Feature Configuration
features:
  numeric_features:
    - "Source Port"
    - "Destination Port"
    - "Protocol"
    - "Flow Duration"
    - "Total Fwd Packets"
    - "Total Backward Packets"
    - "Total Length of Fwd Packets"
    - "Total Length of Bwd Packets"
    - "Fwd Packet Length Max"
    - "Fwd Packet Length Min"
    - "Fwd Packet Length Mean"
    - "Bwd Packet Length Max"
    - "Bwd Packet Length Min"
    - "Bwd Packet Length Mean"
    - "Flow Bytes/s"
    - "Flow Packets/s"
    - "Flow IAT Mean"
    - "Flow IAT Min"
    - "Fwd IAT Total"
    - "Fwd IAT Mean"
    - "Fwd IAT Min"
    - "Bwd IAT Total"
    - "Bwd IAT Mean"
    - "Bwd IAT Std"
    - "Bwd IAT Max"
    - "Fwd PSH Flags"
    - "Bwd PSH Flags"
    - "Fwd URG Flags"
    - "Bwd URG Flags"
    - "Fwd Header Length"
    - "Fwd Packets/s"
    - "Bwd Packets/s"
    - "Min Packet Length"
    - "Max Packet Length"
    - "Packet Length Variance"
    - "FIN Flag Count"
    - "SYN Flag Count"
    - "RST Flag Count"
    - "PSH Flag Count"
    - "ACK Flag Count"
    - "URG Flag Count"
    - "CWE Flag Count"
    - "ECE Flag Count"
    - "Down/Up Ratio"
    - "Average Packet Size"
    - "Avg Fwd Segment Size"
    - "Fwd Header Length.1"
    - "Fwd Avg Bytes/Bulk"
    - "Fwd Avg Packets/Bulk"
    - "Fwd Avg Bulk Rate"
    - "Bwd Avg Bytes/Bulk"
    - "Bwd Avg Packets/Bulk"
    - "Bwd Avg Bulk Rate"
    - "Subflow Fwd Packets"
    - "Subflow Fwd Bytes"
    - "Subflow Bwd Bytes"
    - "Init_Win_bytes_forward"
    - "Init_Win_bytes_backward"
    - "act_data_pkt_fwd"
    - "min_seg_size_forward"
    - "Active Mean"
    - "Active Std"
    - "Active Max"
    - "Idle Mean"
    - "Idle Std"
    - "Idle Max"
  categorical_features: []  # Empty as we're only using numerical features
  target: "Label"

# Model Configuration
model:
  name: "RandomForest"
  params:
    n_estimators: 100
    max_depth: null  # null for None in YAML
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1
  
# Training Configuration
training:
  batch_size: 1024
  num_epochs: 10
  early_stopping_rounds: 10
  cross_validation_folds: 5

# MLflow Configuration
mlflow:
  tracking_uri: "./mlruns"
  experiment_name: "ddos_detection"

# Logging Configuration
logging:
  level: "INFO"
  log_path: "logs/app.log"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false 