name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Create test directories and files
      run: |
        mkdir -p data/raw
        mkdir -p data/processed
        mkdir -p models
        mkdir -p reports/figures
        mkdir -p reports/results
        touch data/raw/network_traffic.csv
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 